### ISSUE TITLE
d

### ISSUE THREAD

**Issue by rambabu2107** [microsoft/vscode-azurearmtools#1486] opened 2022-05-08 14:56 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.codeLens.gotoParameterValue
Error type: Error
Error Message: cannot open file:///c%3A/users/hp/desktop/armmm/azuredeploy.parameters.json. Detail: Unable to read file 'c:\users\hp\desktop\armmm\azuredeploy.parameters.json' (Error: Unable to resolve nonexistent file 'c:\users\hp\desktop\armmm\azuredeploy.parameters.json')

Version: 0.15.6
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.67.0
Language: en

<details>
<summary>Call Stack</summary>

```
d.$tryOpenDocument workbench.desktop.main.js:2731:77104
```

</details>

**Comment by StephenWeatherford** [comment] 2022-05-10 21:52
Dupe of #1483

**Closed by StephenWeatherford** 2022-05-10 21:52 UTC
Labels: needs author feedback
