### ISSUE TITLE
Microsoft.Authorization/roleAssignments is unrecognized (should be fixed with new schema snapshot)

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/vscode-azurearmtools#1366] opened 2021-09-07 21:09 UTC
I'm not fully certain whether this is an issue with this extension or https://github.com/Azure/azure-resource-manager-schemas; apologies if it's in the wrong place.

When creating a [role assignment](https://docs.microsoft.com/en-us/azure/templates/microsoft.authorization/roleassignments?tabs=json) in ARM templates, the `type` is highlighted as invalid:
![Invalid Microsoft.Authorization/roleAssignments type](https://user-images.githubusercontent.com/2766036/132410919-de41fb9d-12c7-4c2d-99cc-f80644b6edbc.png)

It's very clearly valid since 1) the deployment succeeds and 2) it's in the ARM template documentation.

(Possibly related: the API versions listed in the documentation don't line up with the versions accepted with Azure, which is whacky...)

I'm using v0.15.2 of the extension.

**Comment by StephenWeatherford** [comment] 2021-09-07 23:36
Unfortunately that's generally caused by https://github.com/Azure/azure-resource-manager-schemas/issues.  Could you port this bug there and provide a link here so we can track?  Thanks!

**Comment by 50Wliu** [comment] 2021-09-08 14:13
https://github.com/Azure/azure-resource-manager-schemas/issues/1889

**Comment by StephenWeatherford** [comment] 2021-09-09 16:46
Appears to be fixed in schemas, so this is blocked by #1324.

**Closed** 2021-11-10 21:25 UTC
Labels: schema
