### ISSUE TITLE
tab completion of params/vars wipes out remainder of string

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/vscode-azurearmtools#349] opened 2019-10-25 22:06 UTC
Start with the following expression:

            "[resourceId('Microsoft.Network/virtualNetworks', parameters('subnet2Name'))]",

Put the cursor inside the first paren for the resourceId function, I want to add the resourceGroupName parameter for the function.  So type in *parameters('*

After typing the first single quote, press CTRL+SPACE and select a param to tab complete.  The namespace will be erased.

It looks like we have a few chars we look to terminate the autocomplete, but I think if we simply don't erase anything that might be fine.  Just complete the param name, closing single quote and closing paren.

**Comment by neilpeterson** [comment] 2020-03-17 18:48
@bmoore-msft I cannot reproduce this in recent builds. Can you re-confirm that you are still seeing this as an issue?

**Comment by bmoore-msft** [comment] 2020-03-18 22:27
yes, still repros in the build I have v0.8.4

**Comment by StephenWeatherford** [comment] 2020-04-29 19:51
Not positive this is unexpected behavior...

**Comment by StephenWeatherford** [comment] 2020-08-03 23:49
@neilpeterson @bmoore-msft
Technically this is correct behavior.  Consider this:
```
"[parameters('<CURSOR>parameter1')]"
```
If you type CTRL+SPACE and replace with 'subnet2Name', the extension marks the entire current string literal for replacement (`'parameter1'`).

Above, after typing `parameters('`, you get this (because vscode adds the closing `'` - same behavior in typescript):
```
    "[resourceId(parameters('<CURSOR>''Microsoft.Network/virtualNetworks', parameters('subnet2Name'))]",
```
Same as above, the span to replace is the entire current string literal, which is `'''Microsoft.Network/virtualNetworks'` (since two single quotes together are an escape for a single quote).  Thus you get the behavior above.

Need to get a better sense of when users feel the behavior is wrong.  If we need to, we would special-case this scenario's replacement span, or maybe handle the parameters(' replacement differently?

**Comment by StephenWeatherford** [comment] 2020-08-11 01:32
Ignore the above, we shouldn't be replacing the entire string literal.  I could swear vscode used to do it that way...??

**Comment by StephenWeatherford** [comment] 2020-10-08 16:20
Still repros.

**Closed** 2020-10-08 18:27 UTC
Labels: P1, bug, extension, intellisense
