### ISSUE TITLE
The "Select/Create Parameter File..." in status bar is inconsistent with context menu and command list

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#764] opened 2020-06-05 09:41 UTC
**OS:** Mac/Win 10
**Build:** 20200604.33

**Repro Steps:**
Check command "Select/Create Parameter File..." in status bar, context menu and command list.

**Expect:**
The "Select/Create Parameter File..." in status bar is consistent with context menu and command list.

**Actual:**
The "Select/Create Parameter File..." in status bar is inconsistent with context menu and command list.
![image](https://user-images.githubusercontent.com/62053665/83834120-22a12680-a720-11ea-8918-7816cb7eb2d5.png)
![image](https://user-images.githubusercontent.com/62053665/83834132-27fe7100-a720-11ea-8ef3-8f0d90171c1f.png)
![image](https://user-images.githubusercontent.com/62053665/83834137-2af96180-a720-11ea-845d-b62f1e3e0413.png)

**Comment by StephenWeatherford** [comment] 2020-06-05 17:04
@neilpeterson What do you think about this?  Never really been happy with the "Select/Create Parameter File" menu, but maybe it's just me.

**Comment by neilpeterson** [comment] 2020-06-05 18:41
As for the initial issue, I like the status bar behavior (contextual based on current mapping). The discrepancy does not bother me.

The wording 'Select/Create Parameter File...' I feel similar Stephen, but am not sure what the update would be without separating functionality (select / create), which I would not want to do.

Perhaps 'Manage parameter file mapping', however that is not very descriptive.

My vote here would be close this as intended functionality unless we think that the wording is confusing people / contributing to lack of usage. Stephen if you think that may be the case I would be happy to take a customer pulse / perform the research.

**Comment by StephenWeatherford** [comment] 2020-06-05 19:16
Do you think we should add Select/Create to the status bar as well?  If not, go ahead and close.  Thx.

**Comment by neilpeterson** [comment] 2020-06-05 19:35
On second look, yeah, let's change it for consistency.

**Closed** 2020-06-06 23:34 UTC
Labels: AT-CTI
