### ISSUE TITLE
Default completion for dependsOn is a string with a single space

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#926] opened 2020-08-26 01:01 UTC
```
"resources": [
    {
      "name": "[parameters('omsWorkspaceName')]",
      "type": "Microsoft.OperationalInsights/workspaces",
      "apiVersion": "2015-11-01-preview",
      "location": "[parameters('workspaceRegion')]",
      "properties": {
        "sku": {
          "name": "[parameters('omsSku')]"
        }
      },
      "dependsOn": [
      ]
    },
```
![image](https://user-images.githubusercontent.com/6913354/91242646-d3eea180-e6fc-11ea-8aca-580682e6a6c7.png)
![image](https://user-images.githubusercontent.com/6913354/91242686-e537ae00-e6fc-11ea-95a9-7d93dbdae13c.png)

**Comment by StephenWeatherford** [comment] 2020-08-26 01:02
Unlike #678, this one actually adds a string with a space in it instead of an empty string.  Schema?

**Comment by jodavis** [comment] 2020-09-29 20:23
This is a dupe of another issue we're tracking.

**Closed by jodavis** 2020-09-29 20:23 UTC
